server:
  port: 8084

spring:
  application:
    name: vault-service
  datasource:
    url: ${MYSQL_URL:jdbc:h2:mem:keyvault_vault;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${MYSQL_USER:sa}
    password: ${MYSQL_PASSWORD:}
    driver-class-name: ${MYSQL_DRIVER:org.h2.Driver}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
